# Generated by Django 5.0.3 on 2024-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('pdf_attachment', models.FileField(blank=True, null=True, upload_to='product_pdfs/')),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
