# Generated by Django 5.0.3 on 2024-04-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('suggestion_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Enter tags separated by commas.', max_length=255)),
                ('respond', models.CharField(blank=True, help_text='Enter type separated by commas.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('suggestion_details', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_type',
            field=models.CharField(blank=True, help_text='Enter type separated by commas.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter tags separated by commas.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tech',
            field=models.CharField(blank=True, help_text='Enter type tech by commas.', max_length=255),
        ),
    ]
