# Generated by Django 5.0.3 on 2024-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feedback_suggestion_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
