# Generated by Django 5.0.3 on 2024-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_emp_id_userprofile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='client_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='suggestion_id',
            new_name='sent_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='respond',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
