# Generated by Django 5.0.3 on 2024-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_client_id_feedback_rec_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_id',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Vendor'), (2, 'Client')]),
        ),
    ]
