# Generated by Django 5.0.1 on 2024-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCitisoft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('reviewer', 'Reviewer')], default='customer', max_length=20),
        ),
    ]
