# Generated by Django 5.0.1 on 2024-03-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCitisoft', '0003_alter_customuser_email_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
